# Generated by Django 4.2.6 on 2023-11-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDate', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.week'),
        ),
    ]
